# Generated by Django 5.1.4 on 2024-12-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='subcategory',
        ),
    ]
